### ISSUE TITLE
Automate AUR releases

### ISSUE THREAD

**Issue by mgrachev** [dotenv-linter/dotenv-linter#116]
@mstruebing Hi there!

Is it possible to automate releases for [dotenv-linter-bin](https://aur.archlinux.org/packages/dotenv-linter-bin) via GitHub Actions?

What do you think about it?

**Comment by mstruebing** [comment]
I think the only way would be to create a "bot"-account for the AUR and adding an SSH-key.
Then creating a GitHub Action with this SSH-key as a secret - cloning the AUR repository while the pipeline is running - or maybe using a git sub-module - doing the necessary steps and pushing it back to the AUR.

Do you think that is suitable?

**Comment by mgrachev** [comment]
@mstruebing Thank you! I like this approach.

Another question - Can we do that using the OS `ubuntu` https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources?

And would you like to implement it?

**Comment by mstruebing** [comment]
I would like to, but I think I can't find time before next week.

**Comment by mgrachev** [comment]
Thank you! Of course, as soon as you can.

**Comment by mstruebing** [comment]
Hey @mgrachev, I think in order to work on this I need access rights to the repository to create secrets in GitHub actions. Could you give me the rights temporarily until I've finished working on that issue?
After that, I would send you the key pair via send.firefox.com. (I will not do anything evil! :))

**Comment by mgrachev** [comment]
@mstruebing Hi! I've just done it.

**Comment by mstruebing** [comment]
Just FYI, the release to the AUR worked :tada:

**Comment by mgrachev** [comment]
@mstruebing You have done a great work! Thanks a lot! 🔥
