### ISSUE TITLE
Promotion

### ISSUE THREAD

**Issue by mgrachev** [dotenv-linter/dotenv-linter#130]
Hi there!

I would like that more people will know about this project.

What I have already done for this:
- [x] Added the project to [caramelomartins/awesome-linters](https://github.com/caramelomartins/awesome-linters/pull/74);
- [x] Added the project to [reviewdog/reviewdog](https://github.com/reviewdog/reviewdog/pull/431);
- [x] Added the project to [sdras/awesome-actions](https://github.com/sdras/awesome-actions/pull/298);
- [x] Added the project to [rust-unofficial/awesome-rust](https://github.com/rust-unofficial/awesome-rust/pull/786);
- [x] Wrote about the project on [Twitter](https://twitter.com/mgrachev/status/1241700876244434951);
- [x] Wrote an article on [my blog](https://www.mgrachev.com/2020/04/20/dotenv-linter);
- [x] Wrote an article on [my company's blog](https://evrone.com/dotenv-linter);
- [x] Wrote an article on [Dev.to](https://dev.to/ricknoln/dotenv-linter-looking-after-the-environment-for-you-5gk2);
- [x] Posted to Reddit ([rust](https://www.reddit.com/r/rust/comments/g5eq8d/opensourcing_dotenvlinter_lightningfast_tool_to), [programming](https://www.reddit.com/r/programming/comments/g5eyza/opensourcing_dotenvlinter_a_lightningfast_tool_to));
- [x] Posted to [HackerNews](https://news.ycombinator.com/item?id=22923519);
- [x] [This Week in Rust](https://this-week-in-rust.org/blog/2020/04/21/this-week-in-rust-335/);
- [ ] What else?

What I haven't done because COVID-19:
<s>- [ ] Speak about the project at conferences/meetups.</s>

I need your advice. Do you know any other ways to promote the project?

**Comment by mstruebing** [comment]
Posting it on Reddit/HackerNews can also lead to a bunch of attention.
Getting in touch with someone who writes a weekly curated rust newsletter and ask if they could include the project in the next issue.
Blogposts are also good to go a little more in depth.

**Comment by mgrachev** [comment]
@mstruebing Thanks a lot! I have updated the first message.

I guess we can promote the project regardless of the programming language.
Do you know any newsletters for any languages?

**Comment by mgrachev** [comment]
I found this one https://github.com/zudochkin/awesome-newsletters
