### ISSUE TITLE
Trailing whitespace check?

### ISSUE THREAD

**Issue by pineapplethief** [dotenv-linter/dotenv-linter#150]
On one hand, it's trivial to setup text editor to trim trailing whitespace on save.
On the other hand, I, having this option set in my editor, constantly see trailing whitespace in other people projects, mostly as a gitspam of removing it from files I worked on. Apparently many developers don't care about trailing whitespace at all.
I'm not so sure if this is a needed check for .env files, but it could be potentially useful. I can't think off top of my head of any good reason to allow trailing whitespace for env key values.

**Comment by mstruebing** [comment]
I think it's a good idea to integrate. Thank you for that idea.

**Comment by mgrachev** [comment]
@pineapplethief Thank you! It's a good idea! I've assigned this issue to you.

**Comment by mgrachev** [comment]
@pineapplethief Is there any progress?

**Comment by pineapplethief** [comment]
@mgrachev sorry for long delay, but I think I did it
https://github.com/dotenv-linter/dotenv-linter/pull/190
