### ISSUE TITLE
Please add a newline at end of file check

### ISSUE THREAD

**Issue by kjedamzik** [dotenv-linter/dotenv-linter#152]
I would be nice to have a check that makes sure there is a newline at end of file

**Comment by mgrachev** [comment]
@kjedamzik 👋Thank you for the idea!

Would you like to do it?

**Comment by mgrachev** [comment]
@uhbif19 Yes, you are right.
It needs to implement another checker which will check the last character of the file.

Please note that the current implementation uses the [reader.lines](https://github.com/mgrachev/dotenv-linter/blob/master/src/lib.rs#L115) method which returns a string without a newline.
https://doc.rust-lang.org/std/io/trait.BufRead.html#method.lines

**Comment by uhbif19** [comment]
> which will check the last character of the file

Not sure if this is enough. If last line will be `something\n`, checking for last character will lead to false result.

**Comment by mgrachev** [comment]
> > which will check the last character of the file
> 
> Not sure if this is enough. If last line will be `something\n`, checking for last character will lead to false result.

Yes, you are right. It needs to check two last characters.

**Comment by mstruebing** [comment]
What should happen if the ending of the file is something like:

`something\n\n`

should this be valid?

**Comment by mgrachev** [comment]
> What should happen if the ending of the file is something like:
> 
> `something\n\n`
> 
> should this be valid?

I guess yes

**Comment by uhbif19** [comment]
@mgrachev

> It needs to check two last characters.

What about `\r\n` style? Should it be supported?

https://en.wikipedia.org/wiki/Newline#Issues_with_different_newline_formats

**Comment by mstruebing** [comment]
I would say yes:

`\r`, `\r\n` and `\n` should all be supported.

**Comment by evgeniy-r** [comment]
I have taken this issue.
