### ISSUE TITLE
Update source url for dotenv-linter-git

### ISSUE THREAD

**Issue by mgrachev** [dotenv-linter/dotenv-linter#162]
<img width="780" alt="Screenshot 2020-04-22 at 10 15 56" src="https://user-images.githubusercontent.com/700998/79952519-3ac82980-8483-11ea-8127-e3ff8067cab5.png">

It needs to update the source url from https://github.com/mgrachev/dotenv-linter to https://github.com/dotenv-linter/dotenv-linter

**Comment by mstruebing** [comment]
It's updated, see: https://aur.archlinux.org/packages/dotenv-linter-git/

**Comment by mgrachev** [comment]
@mstruebing Thank you! And please do the same in the https://aur.archlinux.org/packages/dotenv-linter-bin repository

**Comment by mstruebing** [comment]
Also done right now.

**Comment by mgrachev** [comment]
@mstruebing Sorry, but I don't see any changes on this page https://aur.archlinux.org/packages/dotenv-linter-bin.

**Comment by mstruebing** [comment]
Can you see it now?

**Comment by mgrachev** [comment]
> Can you see it now?

Yes, now I see 🙂
