### ISSUE TITLE
New check: "Extra blank line"

### ISSUE THREAD

**Issue by evgeniy-r** [dotenv-linter/dotenv-linter#167]
More than one empty line in a row.
Maybe, this check will be useful (some other linters have it).

**Comment by mstruebing** [comment]
Just for clarification, do you mean something like this:

```
// valud
KEY=value

OTHER_KEY=value

// invalid
KEY=value


OTHER_KEY=value
```

**Comment by evgeniy-r** [comment]
Yes, exactly.

**Comment by mgrachev** [comment]
@evgeniy-r It's a good idea! Thank you! Would you like to implement it? 😉

**Comment by evgeniy-r** [comment]
Yes, I can implement it, when we finish with https://github.com/dotenv-linter/dotenv-linter/pull/170.

**Comment by evgeniy-r** [comment]
I have taken this one.
