### ISSUE TITLE
disabling rules ?

### ISSUE THREAD

**Issue by ypann** [dotenv-linter/dotenv-linter#168]
hi, this is a proposal.

it would be nice to have the possibility to disable some checks like the Unordered Key one.
Having unsorted keys in a .env does not make it invalid, and most of the time, we prefer grouping keys by block instead : like one block for database vars, another block for some used API vars, etc...

We would like to use dotenv-linter in shared CI/CD, but can't because of this rule which is incompatible with choices that we already made in a lot of our projects. So what we would need is something like a CLI arg to disable checks :

`dotenv-linter --ignore="UnsortedKey,Xxx,Yyy" `
or 
`dotenv-linter --disable="UnsortedKey,Xxx,Yyy" `

it could be paired with an ability to disable checks inline direclty from the .env itself , using a formatted comment, something like :
`# dotenv-linter:disable UnsortedKey,Xxx,Yyy `
which most of code linters support.

It also could be paired with the ability to have a dotenv-linter config file like .doten-linter.yaml pushed in projects.

but what we really need is the arg ;)

**Comment by mgrachev** [comment]
@ypann It's a good idea, thank you.

We plan to release this feature in the next release.

**Comment by rafaelmaeuer** [comment]
> # dotenv-linter:disable UnsortedKey,Xxx,Yyy

Was this inline exclusion, implemented sometime? I am looking for exactly that option, as I have a setup where I cannot use parameter --exlude and --ignore...

**Comment by DDtKey** [comment]
@rafaelmaeuer you can check the documentation here: https://dotenv-linter.github.io/#/usage/check?id=skip-checks
It's possible to inline exclusion to `.env` file for a specific set of variables

**Comment by rafaelmaeuer** [comment]
thanks for pointing out
