### ISSUE TITLE
Add check: QuoteCharacter

### ISSUE THREAD

**Issue by mgrachev** [dotenv-linter/dotenv-linter#171]
Example:

```env
# .env

# Wrong
FOO='BAR'
FOO="BAR"

# Correct
FOO=BAR
```

This check should display a message:
> .env:1 The value is wrapped in quotes
> .env:2 The value is wrapped in quotes

**Comment by sourabhmarathe** [comment]
I can give this a shot

**Comment by sourabhmarathe** [comment]
#174 is ready now
