### ISSUE TITLE
Check files not from the current directory

### ISSUE THREAD

**Issue by evgeniy-r** [dotenv-linter/dotenv-linter#179]
I noticed that we can't check a file not from the current directory (or its subdirectories):

```
:~$ dotenv-linter 1.env
1.env:3 LowercaseKey: The fOO key should be in uppercase
:~$ cd subd
:~/subd$ dotenv-linter ~/1.env
:~/subd$
```

It is because `let strip_path = match result` in `lib.rs` (`StripPrefixError`).

Is this done on purpose?

**Comment by mgrachev** [comment]
How, in your opinion, should dotenv-linter behave in this case?

**Comment by evgeniy-r** [comment]
I think if the linter will check these files, it will be more understandable and predictable behavior.
At least, such behaviour should be described in the command help (but it is better to fix it - it doesn't look like a complicated task).
I understand that this is a rather rare case, but it looks confusing when you run into this issue.

We have at least two options:
* display the full path;
* use "..." for some path parts when it is very long.

I like the first one (however, I think that it is better then just ignoring these files).

**Comment by mgrachev** [comment]
Example if we display the full path:
```bash
$ dotenv-linter .env ../../.env
/Users/mgrachev/dev/rust/mgrachev/dotenv-linter/.env:2 ExtraBlankLineChecker: Extra blank line detected
/Users/mgrachev/dev/rust/mgrachev/dotenv-linter/.env:3 LeadingCharacter: Invalid leading character detected
/Users/mgrachev/dev/rust/mgrachev/dotenv-linter/.env:5 ExtraBlankLineChecker: Extra blank line detected
/Users/mgrachev/dev/rust/mgrachev/dotenv-linter/.env:6 ExtraBlankLineChecker: Extra blank line detected
/Users/mgrachev/dev/rust/mgrachev/dotenv-linter/.env:7 EndingBlankLine: No blank line at the end of the file
.env:1 KeyWithoutValue: The 1FOO key should be with a value or have an equal sign
.env:1 LeadingCharacter: Invalid leading character detected
.env:1 EndingBlankLine: No blank line at the end of the file
```

To be honest, it looks a bit ugly.

**Comment by evgeniy-r** [comment]
Maybe. 

But it is still better then the linter just ignored this file. And it is a rather rare case.

Also we can want to use some linux commands on output (e.g. `head`, `tail`, `cut`) and so full paths are better.

Finally, we can add some formatting options in the future, that can fix this ugliness (if needed).

**Comment by mgrachev** [comment]
I like this output format more:
```bash
$ dotenv-linter .env ../../.env
../../.env:2 ExtraBlankLineChecker: Extra blank line detected
../../.env:3 LeadingCharacter: Invalid leading character detected
../../.env:5 ExtraBlankLineChecker: Extra blank line detected
../../.env:6 ExtraBlankLineChecker: Extra blank line detected
../../.env:7 EndingBlankLine: No blank line at the end of the file
.env:1 KeyWithoutValue: The 1FOO key should be with a value or have an equal sign
.env:1 LeadingCharacter: Invalid leading character detected
.env:1 EndingBlankLine: No blank line at the end of the file
```

And we can add an option to show the full path of the file in the future.

**Comment by evgeniy-r** [comment]
It also allows you to get the exact location of the file (from the current directory).

So I think this will be OK too.

**Comment by mgrachev** [comment]
Great! I would like to see these changes in the next release 2.0.0.

**Comment by DDtKey** [comment]
This task has not yet been assigned?
I could be engaged in implementation, but, apparently, I need to wait for the review for #207 (acceptance or rejection), because there is an affected part.
