### ISSUE TITLE
EndingBlankLineChecker: refactor last line check logic

### ISSUE THREAD

**Issue by DDtKey** [dotenv-linter/dotenv-linter#204]
At the moment, to apply the checks of the last line, the logic goes beyond the scope of `EndingBlankLineChecker`. 
There are additional external conditions for applying this check in the `checks::run` function.
This distinguishes this check from the general checks API.

I suggest adding a field with a total number of lines to `FileEntry`, like:
`pub total_lines: usize,`

In turn, `impl LineEntry`, referring to `FileEntry` (#203 very useful :rocket:), can implement something like this:
```
pub fn is_last_line(&self) -> bool {
    self.file.total_lines == self.number
}
```

Thus, we will enable the verification of the last line inside "EndingBlankLineChecker" and any checker in the future, just can add next:
`if line.is_last_line() {...}`

In addition to all this, a pre-calculated total number of lines will allow us to allocate a vector with initial capacity, as it:
```
let total_lines = reader.lines().count();
let mut lines: Vec<LineEntry> = Vec::with_capacity(total_lines);
```

**Comment by evgeniy-r** [comment]
Just in case, `reader.lines()` returns an iterator, so it seems that to get `count()` we must read all lines.

**Comment by DDtKey** [comment]
> Just in case, `reader.lines()` returns an iterator, so it seems that to get `count()` we must read all lines.

In fact, this is just an example. But, in fact, the `lines()` iterator itself is lazy (we don’t load them into memory), but yes, to count, we really need to go through the file anyway.

Otherwise, if you do not count the number of lines, it becomes difficult to put them in `FileEntry` persistently. Updating each `FileEntry` after a pass seems unobvious and redundant.

I think there are other options, but they will have a stronger effect on the current code base, which would like to avoid.

I think for .env files this is not the biggest costs (although it depends on the FS), at the same time, the number of allocations for the vector decreases.

We can still think about it, but it really allows you to generalize the API for checks and there will be no such exception as `EndingBlankLineChecker` and will give this opportunity to future checkers.

I will try to check some concepts and maybe I will find something more optimal.
Solution in the issue is presented only an example.

**Comment by evgeniy-r** [comment]
Actually, I have written the comment because it was my first idea, when I saw this TODO )

We can also read the entire file (with `std::fs::read` for example) and then work with its contents in memory.
