### ISSUE TITLE
Change repository link to the docs

### ISSUE THREAD

**Issue by wesleimp** [dotenv-linter/dotenv-linter#229]
The repository link is currently referencing www.mgrachev.com/projects. It would be nice to have it referencing to the [docs](https://dotenv-linter.github.io).

**Comment by mstruebing** [comment]
I completely agree. It looks like @mgrachev is the only one able to change that.
@mgrachev can you do it?

**Comment by mgrachev** [comment]
Yes, I'll do it soon 🙂

**Comment by mgrachev** [comment]
Done ⚡️
