### ISSUE TITLE
Add fixer: DuplicatedKeyFixer

### ISSUE THREAD

**Issue by DDtKey** [dotenv-linter/dotenv-linter#243]
Implement `trait Fix` to fix warnings caused by `DuplicatedKeyChecker`.
And add this `Fix` to the `fixlist` in [fixes.rs](https://github.com/dotenv-linter/dotenv-linter/blob/cf176993360215596c079873725f4a4b7a48f5b0/src/fixes.rs#L32)

I think this fixer should remove duplicate keys. 
For example:
```
PROFILE_ENV=development
PROFILE_ENV=test
```
After running `DuplicatedKeyFixer` it should look like this:
```
PROFILE_ENV=development
```

Implementation example: [LowercaseKeyFixer](https://github.com/dotenv-linter/dotenv-linter/blob/master/src/fixes/lowercase_key.rs)

**Comment by mgrachev** [comment]
> I think this fixer should remove duplicate keys.

What do you think about commenting a duplicated key instead of removing it?

**Comment by DDtKey** [comment]
> > I think this fixer should remove duplicate keys.
> 
> What do you think about commenting the duplicated key instead of removing it?

Yes, maybe this is a good approach :+1:  
At least until we have backups.
