### ISSUE TITLE
Add fixer: ExtraBlankLineFixer

### ISSUE THREAD

**Issue by DDtKey** [dotenv-linter/dotenv-linter#245]
Implement `trait Fix` to fix warnings caused by `ExtraBlankLineChecker`.
And add this `Fix` to the `fixlist` in [fixes.rs](https://github.com/dotenv-linter/dotenv-linter/blob/cf176993360215596c079873725f4a4b7a48f5b0/src/fixes.rs#L32)

Implementation example: [LowercaseKeyFixer](https://github.com/dotenv-linter/dotenv-linter/blob/master/src/fixes/lowercase_key.rs)

**Comment by diggymo** [comment]
Hi. May I try it if you like?

**Comment by mgrachev** [comment]
> Hi. May I try it if you like?

Sure! 👍

**Comment by diggymo** [comment]
I have a question.

`Fix` trait's function `fix_line` has `_line`argument. But ExtraBlankLineFixer can't use function `fix_line`. Because a warning line needs to be deleted, not modified.

```
    fn fix_line(&self, _line: &mut LineEntry) -> Option<()> {
       // .. 
    }
```

so, is it better to add new function `fn fix_multiple_lines(&self, _line: &mut Vec<LineEntry>) -> Option<()>` in trait `Fix`?

**Comment by DDtKey** [comment]
> I have a question.
> 
> `Fix` trait's function `fix_line` has `_line`argument. But ExtraBlankLineFixer can't use function `fix_line`. Because a warning line needs to be deleted, not modified.
> 
> ```
>     fn fix_line(&self, _line: &mut LineEntry) -> Option<()> {
>        // .. 
>     }
> ```
> 
> so, is it better to add new function `fn fix_multiple_lines(&self, _line: &mut Vec<LineEntry>) -> Option<()>` in trait `Fix`?

In this case, I think you can just override `fix_warnings(&self, warnings: Vec<&mut Warning>,  lines: &mut Vec<LineEntry>)` and specify necessary logic which removes extra lines :)

**Comment by diggymo** [comment]
I'm sorry I didn't notice. Thank you.
