### ISSUE TITLE
Add fixer: LeadingCharacterFixer

### ISSUE THREAD

**Issue by DDtKey** [dotenv-linter/dotenv-linter#248]
Implement `trait Fix` to fix warnings caused by `LeadingCharacterChecker`.
And add this `Fix` to the `fixlist` in [fixes.rs](https://github.com/dotenv-linter/dotenv-linter/blob/cf176993360215596c079873725f4a4b7a48f5b0/src/fixes.rs#L32)

```env
# .env

# Wrong
*RAILS_ENV=development

# Correct (After running `LeadingCharacterFixer` it should look like this)
RAILS_ENV=development
```

Implementation example: [LowercaseKeyFixer](https://github.com/dotenv-linter/dotenv-linter/blob/master/src/fixes/lowercase_key.rs)

**Comment by norraell** [comment]
I would like to take this one.
