### ISSUE TITLE
Add fixer: QuoteCharacterFixer

### ISSUE THREAD

**Issue by DDtKey** [dotenv-linter/dotenv-linter#249]
Implement `trait Fix` to fix warnings caused by `QuoteCharacterChecker`.
And add this `Fix` to the `fixlist` in [fixes.rs](https://github.com/dotenv-linter/dotenv-linter/blob/cf176993360215596c079873725f4a4b7a48f5b0/src/fixes.rs#L32)

```env
# .env

# Wrong
FOO="BAR"

# Correct (After running `QuoteCharacterFixer` it should look like this)
FOO=BAR
```

Implementation example: [LowercaseKeyFixer](https://github.com/dotenv-linter/dotenv-linter/blob/master/src/fixes/lowercase_key.rs)

**Comment by lensvol** [comment]
I can take it if you don't mind. :)

**Comment by DDtKey** [comment]
> I can take it if you don't mind. :)

Of course, we will be glad for any help :relaxed:
