### ISSUE TITLE
Add fixer: TrailingWhitespaceFixer

### ISSUE THREAD

**Issue by DDtKey** [dotenv-linter/dotenv-linter#251]
Implement `trait Fix` to fix warnings caused by `TrailingWhitespaceChecker`.
And add this `Fix` to the `fixlist` in [fixes.rs](https://github.com/dotenv-linter/dotenv-linter/blob/cf176993360215596c079873725f4a4b7a48f5b0/src/fixes.rs#L32)

Implementation example: [LowercaseKeyFixer](https://github.com/dotenv-linter/dotenv-linter/blob/master/src/fixes/lowercase_key.rs)

**Comment by gregcline** [comment]
I'd like to give this a try.
