### ISSUE TITLE
Add fixer: UnorderedKeyFixer

### ISSUE THREAD

**Issue by DDtKey** [dotenv-linter/dotenv-linter#252]
Implement `trait Fix` to fix warnings caused by `UnorderedKeyChecker`.
And add this `Fix` to the `fixlist` in [fixes.rs](https://github.com/dotenv-linter/dotenv-linter/blob/cf176993360215596c079873725f4a4b7a48f5b0/src/fixes.rs#L32)

```env
# .env

# Wrong
RAILS_ENV=development
DEBUG=true

BAR=FOO

# Correct (After running `UnorderedKeyFixer` it should look like this)
DEBUG=true
RAILS_ENV=development

BAR=FOO
```
**Important**: _sorting within groups_

Implementation example: [LowercaseKeyFixer](https://github.com/dotenv-linter/dotenv-linter/blob/master/src/fixes/lowercase_key.rs)

**Comment by evgeniy-r** [comment]
I take this one.
