### ISSUE TITLE
"Lightning-fast because it is written in Rust"

### ISSUE THREAD

**Issue by piegamesde** [dotenv-linter/dotenv-linter#256]
Please remove this line from the README. Writing an application in one programming language over another won't magically make it faster. On the other hand, I've seen this attitude of associating programming languages with their performance cause quite some harm in the past.

**Comment by mstruebing** [comment]
Would you suggest to just remove it or replace it with something else?

**Comment by piegamesde** [comment]
Honestly, I don't care. If it's really that fast, there's no reason to hide it. Some benchmarks or comparison with similar software would give credibility to that claim – simply saying "It's fast" usually isn't enough for people to believe it.

As an example, [from Exa](https://the.exa.website):

> IT’S FAST
> exa queries files in parallel, giving you performance on par with ls.

**Comment by mgrachev** [comment]
>⚡️ Lightning-fast because it is written in Rust 🦀
 
👋 Hi there! Thank you, for your opinion!
I'm sorry, but I think so and I like this phrase 🙂

I've been already working on writing benchmarks to compare `dotenv-linter` with a similar tool.
I'll definitely add benchmarks to the README soon, but for now I'll close this issue ✌️

**Comment by DDtKey** [comment]
To be honest, I don't see magic in this.
This phrase does not mean that you will get worse performance using another language :thinking: 

You are correct that you can write slow code regardless of the programming language.
But Rust follows the concept of zero cost abstraction. Which makes it much easier to write high-performance code and the peculiarities of the language in every possible way "interfere" with writing slow code (_principles of ownership, borrow checker, etc. help the compiler to make many optimizations_).

Considering that this is a CLI tool, where a quick start is important and additional runtimes may be overkill. For example, in such cases, there is little use of a JIT compiler. And in this case, the features of the Rust really do benefit :relaxed: 

Demonstrating performance tests is indeed more revealing and credible than just choosing a language. 
It's good if we have the results of such tests. But I see no problem in the phrase itself :confused:
