### ISSUE TITLE
Display file names being scanned

### ISSUE THREAD

**Issue by gillespiecd** [dotenv-linter/dotenv-linter#268]
Since the program doesn't output anything when files don't have warnings, as a user, I would like to see which files have been scanned, especially in the case of a deeply nested recursive situation.

```
Linting foo.env
Linting nested/bar.env
Linting nested/dir/test.env
```

I'm happy to take this on if owners feel like this would be a useful addition to the project.

**Comment by mgrachev** [comment]
@gillespiecd Thank you for your proposal!

I have some questions:
1. We already display information on how many problems we found. Also, we already have the `--quiet` argument not to display additional information. Maybe this feature should work by default?
2. Will this feature work with only checks?  What about fixers?
3. What the output will look like for different cases? Please give some examples.

**Comment by gillespiecd** [comment]
```
We already display information on how many problems we found. Also, we already have the --quiet argument not to display additional information. Maybe this feature should work by default?
```

This sounds the best to me 👍

**Comment by mgrachev** [comment]
Before that I'd like to see other opinions on this
/cc @dotenv-linter/core

**Comment by mgrachev** [comment]
I'd like to see something like this if we run `dotenv-linter` without any arguments:
```bash
$ dotenv-linter
Checking .env
.env:1 IncorrectDelimiter: The FOO* key has incorrect delimiter

Checking .env.test
.env.test:1 IncorrectDelimiter: The 1FOO* key has incorrect delimiter
.env.test:1 LeadingCharacter: Invalid leading character detected

Found 3 problems
```

If we run `dotenv-linter` with the `--quiet` argument:
```bash
$ dotenv-linter -q
.env:1 LowercaseKey: The test key should be in uppercase
.env.test:1 IncorrectDelimiter: The 1FOO* key has incorrect delimiter
.env.test:1 LeadingCharacter: Invalid leading character detected
```

If we run `dotenv-linter` with the `--fix` argument:
```bash
$ dotenv-linter -f
Fixing .env
Original file was backed up to: ".env_1601369083"

.env:1 LowercaseKey: The test key should be in uppercase

Fixing .env.test
Original file was backed up to: ".env.test_1601369083"

.env.test:1 IncorrectDelimiter: The 1FOO* key has incorrect delimiter
.env.test:1 LeadingCharacter: Invalid leading character detected

All warnings are fixed. Total: 3
```

@dotenv-linter/core What do you think?

**Comment by Anthuang** [comment]
I'd like to give this a try!
