### ISSUE TITLE
Non zero exit code for success

### ISSUE THREAD

**Issue by gillespiecd** [dotenv-linter/dotenv-linter#276]
To reproduce, scan a file with an unfixed error, e.g. extra blank lines:
1. `cargo run -- -f`
2. `echo $?` returns 1

The reason is that this line gets called for several different branches https://github.com/dotenv-linter/dotenv-linter/blob/master/src/main.rs#L51

It doesn't seem correct to return an exit code of 1 unless there is some issue with the code execution.

**Comment by mgrachev** [comment]
Hmm, we've already discussed this topic earlier.
Look at this https://github.com/dotenv-linter/dotenv-linter/issues/47

**Comment by gillespiecd** [comment]
Thanks, I missed that earlier, we can close 👍
