### ISSUE TITLE
ExtraBlankLineFixer with control comments work incorrectly

### ISSUE THREAD

**Issue by DDtKey** [dotenv-linter/dotenv-linter#278]
I found a bug when we run dotenv-linter with control comments(#237) and `--fix` flag (now specific for ExtraBlankLineFixer #260).
This is because the fixer works on all line collection without matching `Warning` line number or re-checking the control comments.

<details>
<summary> Example </summary>

```dotenv
DEBUG_HTTP=true

# dotenv-linter:off ExtraBlankLine



# dotenv-linter:on ExtraBlankLine



DB_NAME=development
```

After run `dotenv-linter -f .env` we will receive next result:

```dotenv
DEBUG_HTTP=true

# dotenv-linter:off ExtraBlankLine

# dotenv-linter:on ExtraBlankLine

DB_NAME=development
```

With output:
```
Fixed warnings:
../../workdir/test/test.env:9 ExtraBlankLine: Extra blank line detected
../../workdir/test/test.env:10 ExtraBlankLine: Extra blank line detected
```
</details>

Ie also fixed warnings in the comment block.

**Simple solution:** in such cases, check control comments additionally.
Perhaps it makes sense to move some of the code into a module.

Or we need to **use a different approach** in correcting and matching, but after other fixers, the line order may change, and changing the line number in `Warning` does not look the best way - this way we will not be able to display the numbers of the original file (unless everything is fixed and the output is needed)
Or, as has already been suggested, run them one after another. But all this **requires more changes.**

Now it is also relevant for #261.

Any suggestions? :thinking:

**Comment by mgrachev** [comment]
Good catch! Thank you 👍

I'm pretty busy right now, I'll think about it soon 🤔

**Comment by mgrachev** [comment]
Maybe we will mark all extra blank lines as deleted and remove them after running all fixers?

I have made the PR with this concept https://github.com/dotenv-linter/dotenv-linter/pull/279 👀

**Comment by DDtKey** [comment]
I like this approach! 
It sounds concise and much easier! :rocket: 

A little later I will look at the PR and think about this, thank you :+1:

**Comment by DDtKey** [comment]
@mgrachev I will draw your attention to the only thing is, it will not help in the case of `UnorderedKey`... :thinking: 
There we have to find another solution. Or make something more universal, hm

**Comment by mgrachev** [comment]
> @mgrachev I will draw your attention to the only thing is, it will not help in the case of `UnorderedKey`... 🤔
> There we have to find another solution. Or make something more universal, hm

Thanks! I will think about it too.
