### ISSUE TITLE
Some fixers can spawn new warnings (e. g. LowercaseKey)

### ISSUE THREAD

**Issue by evgeniy-r** [dotenv-linter/dotenv-linter#285]
Before fix:
```
A1=1
A2=2
a0=0
a2=2

```

After fix:
```
A1=1
A2=2
A0=0
A2=2

```

We will get new `UnorderedKey` and `DuplicatedKey` warnings if we check this file again.

I propose to change the conditions when the `UnorderedKey` and `DuplicatedKey` fixers apply, and also make some changes in the `DuplicatedKey` fixer. 

I will prepare the PR.

**Comment by mgrachev** [comment]
@evgeniy-r Good catch! 👍 Thank you!
