### ISSUE TITLE
New check: Short key

### ISSUE THREAD

**Issue by mgrachev** [dotenv-linter/dotenv-linter#286]
`dotenv-linter` can check `.env` files for short keys (equal to 1 character):

```env
❌ Wrong
A=A

✅ Correct
AB=AB
ABC=ABC
```

@dotenv-linter/core What do you think about it?

**Comment by mstruebing** [comment]
Is this widely accepted practice? I didn't hear about that before

**Comment by mgrachev** [comment]
> Is this widely accepted practice? I didn't hear about that before

I didn't hear about that before too, but from my point of view environment variables with short keys are not informative.

**Comment by mstruebing** [comment]
I'm not against it but I think if we implement this it would be cool to have an opt-in mechanism for that

**Comment by mgrachev** [comment]
> I'm not against it but I think if we implement this it would be cool to have an opt-in mechanism for that

What do you mean? Can you give an example?

**Comment by mstruebing** [comment]
So that you need to explicitly enable this check instead of disabling it.

I think this is a **highly opinionated check** and therefore should not be enabled by default. 
People who want to use it would be able to activate it, say via a flag or configuration file and everyone else wouldn't be bothered by it.

Or do you think it would be good to have this activated by default?

**Comment by mgrachev** [comment]
> So that you need to explicitly enable this check instead of disabling it.
> 
> I think this is a **highly opinionated check** and therefore should not be enabled by default.
> People who want to use it would be able to activate it, say via a flag or configuration file and everyone else wouldn't be bothered by it.

From my point of view, all checks should be enabled by default. If a check should be disabled by default we shouldn't include such checks in our project.

> Or do you think it would be good to have this activated by default?

I don't know. It's just an idea and I'd like to know the opinion about it 🙂

**Comment by DDtKey** [comment]
Thanks for the idea, really such properties do not make sense as a rule, but they are valid and I don't think it's a good idea to consider it a `Warning` by default.


Also, the only way to fix it is to comment out or delete it, but really, the user just needs to think about the new name for variable.

**Comment by mgrachev** [comment]
Agree. Thank you for your opinions! I will close the issue.
