### ISSUE TITLE
Add CARGO_TERM_COLOR to CI

### ISSUE THREAD

**Issue by mgrachev** [dotenv-linter/dotenv-linter#290]
Add env `CARGO_TERM_COLOR` to:
* [CI workflows](https://github.com/dotenv-linter/dotenv-linter/blob/master/.github/workflows/ci.yml)
* [Release workflows](https://github.com/dotenv-linter/dotenv-linter/blob/master/.github/workflows/release.yml)

Links:
https://doc.rust-lang.org/cargo/reference/config.html#termcolor

**Comment by Kitwradr** [comment]
I would like to work on this

**Comment by mgrachev** [comment]
> I would like to work on this

I'm sorry, but @skippednote has already solved this issue 😕
