### ISSUE TITLE
Add colored output and --no-color argument 

### ISSUE THREAD

**Issue by mgrachev** [dotenv-linter/dotenv-linter#291]
Unfinished PR https://github.com/dotenv-linter/dotenv-linter/pull/240

**Comment by Nikhil0487** [comment]
@mgrachev 

 I will look around the code base and give this issue a try.

**Comment by mgrachev** [comment]
> @mgrachev
> 
> I will look around the code base and give this issue a try. Please guide me through any first steps if needed. Thanks.

Thank you! I have assigned this issue to you 😉
