### ISSUE TITLE
Add additional test for LineEntry.get_value

### ISSUE THREAD

**Issue by mgrachev** [dotenv-linter/dotenv-linter#292]
Add an additional test for [LineEntry.get_value](https://github.com/dotenv-linter/dotenv-linter/blob/master/src/common/line_entry.rs#L38) to make sure it works correctly with quotes:
```env
FOO='BAR'
FOO="BAR"
```

**Comment by vvkpd** [comment]
I would like to work on this card, could you please assign to me.
Thanks

**Comment by vvkpd** [comment]
Hey @mgrachev,
                           Thanks for the chance to contribute in this open source project. I made the changes and raised the pr as well. Could you please review it and let me know if there anything else remains in this pr.
Thanks

**Comment by vvkpd** [comment]
Hey @mgrachev 
A small suggestion: Could you please add **hacktoberfest** in topic of _dotenv-linter_ repo?
Background: I am participating in **hacktoberfest 2020**, since this repo does not have hacktoberfest topic that's why My raised pr is not applicable for hacktoberfest 2020.
Thanks

**Comment by mgrachev** [comment]
> Hey @mgrachev
> A small suggestion: Could you please add **hacktoberfest** in topic of _dotenv-linter_ repo?
> Background: I am participating in **hacktoberfest 2020**, since this repo does not have hacktoberfest topic that's why My raised pr is not applicable for hacktoberfest 2020.
> Thanks

I have done it. Thank you for participating! ❤️
