### ISSUE TITLE
Add check_output function for integration tests

### ISSUE THREAD

**Issue by mgrachev** [dotenv-linter/dotenv-linter#293]
Add the `check_output` function similar to [fix_output](https://github.com/dotenv-linter/dotenv-linter/blob/master/tests/common/output.rs#L3) and use it in integration tests. For example:
* https://github.com/dotenv-linter/dotenv-linter/blob/master/tests/checks/extra_blank_line.rs#L28
* https://github.com/dotenv-linter/dotenv-linter/blob/master/tests/checks/ending_blank_line.rs#L35

**Comment by Anthuang** [comment]
Could I take this?

**Comment by mgrachev** [comment]
> Could I take this?

Sure!
