### ISSUE TITLE
Add ability to install the latest version via homebrew

### ISSUE THREAD

**Issue by mgrachev** [dotenv-linter/dotenv-linter#295]
For example:
```bash
$ brew install --HEAD dotenv-linter/tap/dotenv-linter
```

Homebrew formula's repository:
https://github.com/dotenv-linter/homebrew-tap

Links:
https://docs.brew.sh/Formula-Cookbook#unstable-versions-head

**Comment by humancalico** [comment]
Hey @mgrachev, I will work on this.

**Comment by humancalico** [comment]
Oops, didn't see there was an open PR by @jasLogic. I'll work on some other issue
