### ISSUE TITLE
Add action-yamllint

### ISSUE THREAD

**Issue by mgrachev** [dotenv-linter/dotenv-linter#300]
Add `action-yamllint` to lint `yaml` files.

Link:
https://github.com/reviewdog/action-yamllint

**Comment by vk26** [comment]
Hi! I take this )

**Comment by mgrachev** [comment]
@vk26 Do you have any progress on this?

**Comment by vk26** [comment]
@mgrachev Hi! I did PR [#317](https://github.com/dotenv-linter/dotenv-linter/pull/317)
