### ISSUE TITLE
Invalid linting on .envrc (direnv) files

### ISSUE THREAD

**Issue by halostatue** [dotenv-linter/dotenv-linter#323]
[direnv](https://direnv.net) uses `.envrc` files which are bash scripts, and `dotenv-linter` is attempting to parse those. When I ran `dotenv-linter`, I got the following as errors:

```
.envrc:2 KeyWithoutValue: The source_up key should be with a value or have an equal sign
.envrc:4 KeyWithoutValue: The use kerl --auto key should be with a value or have an equal sign
.envrc:5 KeyWithoutValue: The use kiex --auto key should be with a value or have an equal sign
.envrc:6 KeyWithoutValue: The use nvm --auto key should be with a value or have an equal sign
.envrc:7 KeyWithoutValue: The use chruby --auto key should be with a value or have an equal sign
.envrc:10 KeyWithoutValue: The dotenv key should be with a value or have an equal sign
```

All of these are _correct_, because they are functions in either the `direnv` standard library or in an extension that I have on my computer.

As direnv-based `.envrc` files are not merely `.env` files but full bash scripts, it is probably less than ideal that `.envrc` files are included in the default scanning pattern, and I would suggest that a warning be printed if scanning `.envrc` files manually.

The auto-fix for shell functions &c with direnv scripts breaks things badly:

```diff
--- .envrc	2020-10-15 11:48:53.000000000 -0400
+++ .envrc.backup	2020-07-16 22:11:45.000000000 -0400
@@ -1,13 +1,13 @@
 # shellcheck disable=SC2148
-source_up=
+source_up
 
-use chruby --auto=
-use kerl --auto=
-use kiex --auto=
-use nvm --auto=
+use kerl --auto
+use kiex --auto
+use nvm --auto
+use chruby --auto
 
 # use dotenv for compatibility with Docker and Docker Compose
-dotenv=
+dotenv
```

**Comment by mgrachev** [comment]
@halostatue 👋 Thank you for letting us know 👍

To avoid this problem, please run `dotenv-linter` with the `--exclude` argument:
```bash
$ dotenv-linter -e .envrc
```

**Comment by mgrachev** [comment]
@dotenv-linter/core I think we can add `.envrc` to an ignore list by default. What do you think about it?

**Comment by mstruebing** [comment]
Yep, would say so :+1:

**Comment by metalon** [comment]
I wanna take a shot at it
