### ISSUE TITLE
Long recursion possible with cyclic links in dir tree

### ISSUE THREAD

**Issue by ametalon** [dotenv-linter/dotenv-linter#326]
Create a single file and a symbolic link to its containing dir:
```
$ mkdir -p /tmp/project
$ echo 'ohno' > /tmp/project/.env
$ ln -s /tmp/project/ /tmp/project/back_to_root
$ tree -a /tmp/project
/tmp/project
├── back_to_root -> /tmp/project/
└── .env
```

Run linter with recursive search:
```
$ cargo run -- -r /tmp/project/
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/dotenv-linter -r /tmp/project/`
../../../../tmp/project/.env:1 KeyWithoutValue: The ohno key should be with a value or have an equal sign
../../../../tmp/project/back_to_root/.env:1 KeyWithoutValue: The ohno key should be with a value or have an equal sign
../../../../tmp/project/back_to_root/back_to_root/.env:1 KeyWithoutValue: The ohno key should be with a value or have an equal sign
[snipped]

Found 41 problems
```
It follows the link and rechecks the same file again and again.

Possible solutions:
1. Don't follow links
2. Keep track of already visited dirs in canonicalized form

**Comment by mgrachev** [comment]
@ametalon Thank you! I like more the first option.

@dotenv-linter/core What do you think?

**Comment by DDtKey** [comment]
> @ametalon Thank you! I like more the first option.
> 
> @dotenv-linter/core What do you think?

I agree, the first option sounds good.

**Comment by sonro** [comment]
Hi, I would like to fix this issue if it is available.

**Comment by mstruebing** [comment]
Don't follow links sound sufficient I think
