### ISSUE TITLE
Automatic changelog adding of new commits on merge in master

### ISSUE THREAD

**Issue by mstruebing** [dotenv-linter/dotenv-linter#331]
Currently, everyone needs to add their changes themselves to the `CHANGELOG.md` file. As this is tedious work it would be great if that could be automated via a github action on merge in master or something like that.

**Comment by DDtKey** [comment]
That would be really very helpful! :+1: 
I already thought about this, the only thing is not always clear how to automatically classify PR (Added / Changed) :thinking:

**Comment by mstruebing** [comment]
> the only thing is not always clear how to automatically classify PR (Added / Changed) 

That would mean we need to introduce some commit guidelines, which wouldn't be so bad I think.
On the other hand: If the commit message is clear enough, maybe it would be enough to have only a list of commits in the changelog between the versions, but I'm not sure. Any other ideas?

**Comment by mgrachev** [comment]
> That would be really very helpful! 👍
> I already thought about this, the only thing is not always clear how to automatically classify PR (Added / Changed) 🤔
> 
> In fact, this can be done even at the stage of the release build, in order to avoid unnecessary bot commits(per each PR) and line conflicts, writing the entire block of changes at once.

There are two options to do that:
1. Follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0) rules and uses prefixes: `feat` and `fix`. To ensure that contributors follow these rules we can add the [commitlint](https://github.com/conventional-changelog/commitlint);
2. Uses labels like `feature` and `changes`.

I like more the first option.

**Comment by mgrachev** [comment]
> In fact, this can be done even at the stage of the release build, in order to avoid unnecessary bot commits(per each PR) and line conflicts, writing the entire block of changes at once.

I would think more how to implement this one, because I wouldn't like to have a lot of bot commits 😅

**Comment by mstruebing** [comment]
I personally like conventional commits :)

**Comment by DDtKey** [comment]
I also actively use conventional commits in other projects, so I will gladly support this idea 🙂
