### ISSUE TITLE
Proposal: Using subcommands intead of flags

### ISSUE THREAD

**Issue by mgrachev** [dotenv-linter/dotenv-linter#333]
### Problems
1. We now have a few flags, which are essentially subcommands: `--fix` & `--show-checks`;
2. Some flags don't work with other. Example: `$ dotenv-linter --no-backup`;
3. Adding new commands like `compare` confuses the code even more.

### Solution
**Breaking changes**: Using subcommands intead of flags.

Checking `.env` files will by default have no subcommand:

```bash
$ dotenv-linter
```

Fixing `.env` files will have the `fix` subcommand:

```bash
$ dotenv-linter fix
```

Showing checks will have the `checks` subcommand:

```bash
$ dotenv-linter checks
```

### Additional changes
Move to the [clap](https://github.com/clap-rs/clap) `v3.0.0-beta.2` - there are a lot of new changes like:
* Generate a CLI simply by defining a struct;
* Auto-generated completion scripts (using `clap_generate`);
* Derive macros;
* Support for building CLIs from YAML;
* Automatic Version from `Cargo.toml`.

What do you think?

**Comment by DDtKey** [comment]
Are we talking about `clap` subcommands? I would try to implement this if you haven't started implementing it yet.
I’ll just wait for a description of how you want it (but it seems I’m guessing :thinking:)

**Comment by mgrachev** [comment]
> Are we talking about `clap` subcommands? I would try to implement this if you haven't started implementing it yet.
> I’ll just wait for a description of how you want it (but it seems I’m guessing 🤔)

I'm sorry, but I already have a working prototype and don't have time to write the description 🙂

if you are looking for something to do, then I can sugget you to implement on-the-fly output 😉
What do you think?

But before that, please open an issue for "on-the-fly output" and describe what you want to do 🙏
Also, we have to merge this PR https://github.com/dotenv-linter/dotenv-linter/pull/311, but I see one unresolved comment https://github.com/dotenv-linter/dotenv-linter/pull/311#discussion_r509367381 
I think we can make these changes as part of your task. What do you think? 🤔

**Comment by DDtKey** [comment]
> if you are looking for something to do, then I can sugget you to implement on-the-fly output 😉
> 
> What do you think?
> 
> 
> 
> But before that, please open an issue for "on-the-fly output" and describe what you want to do 🙏
> 
> Also, we have to merge this PR https://github.com/dotenv-linter/dotenv-linter/pull/311, but I see one unresolved comment https://github.com/dotenv-linter/dotenv-linter/pull/311#discussion_r509367381 
> 
> I think we can make these changes as part of your task. What do you think? 🤔

I agree, we can do it in the future PR.  Soon, in this case, I will create an issue and start work 🙂

**Comment by mstruebing** [comment]
Shouldn't be `check` the default command which is used when no other command is passed?
I mean, it's basically a linter to exactly do that.
Or what are your reasons to split commands?

**Comment by mgrachev** [comment]
> Shouldn't be `check` the default command which is used when no other command is passed?
> I mean, it's basically a linter to exactly do that.
> Or what are your reasons to split commands?

It make sense 🤔

**Comment by mgrachev** [comment]
@DDtKey @mstruebing I have just updated the description of this issue. Please take a look 🙂

**Comment by mstruebing** [comment]
That sounds good to me :+1: 

Just a question as I'm not to opinionated about it: should we really use a beta version (clap) or wait until a stable one is released?

**Comment by DDtKey** [comment]
Really sounds good 🚀 
I think it would be quite logical to wait for a stable version.  
We can generally implement in beta, but not release until stabilization `clap` 🤔

**Comment by mgrachev** [comment]
I decided to postpone updating clap, because we can wait for a new version for a very long time 🙂
