### ISSUE TITLE
Support export prefix?

### ISSUE THREAD

**Issue by coolaj86** [dotenv-linter/dotenv-linter#337]
The [original dotenv](https://github.com/bkeepers/dotenv), and many (most?) of the [clones](https://github.com/joho/godotenv) support the `export` prefix in a .env file (which is also compatible with bash, zsh, fish, etc).

It appears that `dotenv-linter` does not:

`.env`:

```bash
export GITHUB_TOKEN=xxxxxxxx
```

```bash
dotenv-linter --version
dotenv-linter 2.2.1

dotenv-linter .env
```

```txt
dotenv-linter ~/.config/goreleaser/env
../.config/goreleaser/env:1 IncorrectDelimiter: The export GITHUB_TOKEN key has incorrect delimiter
../.config/goreleaser/env:1 LowercaseKey: The export GITHUB_TOKEN key should be in uppercase
```

Unfortunately there's no RFC for .env but shouldn't this, as a linter, support the same parsing rules as canonical dotenv?

**Comment by mgrachev** [comment]
@coolaj86 Thank you for your proposal!

@dotenv-linter/core What do you think?

**Comment by mstruebing** [comment]
I honestly never heard of it but if it is widely used, as it seems, we should support it in my opinion.

**Comment by mgrachev** [comment]
@coolaj86 @dotenv-linter/core I have included this feature in the next release [v3.0.0](https://github.com/dotenv-linter/dotenv-linter/issues/334).

**Comment by skonik** [comment]
Hi. I would like to implement this

**Comment by mstruebing** [comment]
Cool! @skonik if you need any help or starting points feel free to ask.
