### ISSUE TITLE
Support multi-line values

### ISSUE THREAD

**Issue by mgrachev** [dotenv-linter/dotenv-linter#339]
[bkeepers/dotenv](https://github.com/bkeepers/dotenv), [motdotla/dotenv](https://github.com/motdotla/dotenv), [python-dotenv](https://github.com/theskumar/python-dotenv) and [stackbuilders/dotenv-hs](https://github.com/stackbuilders/dotenv-hs) support multi-line values. For example:

```bash
MULTILINE="new\nline"
```

**Comment by mstruebing** [comment]
We would need to read files at once and not line by line and write a parser I think which parses the `.env` file in our internal code structure I think. Sounds a bit complicated, I've never written a parser in my life but I would be interested.

Any other ideas, maybe some more lightweight solutions?

**Comment by mgrachev** [comment]
> Any other ideas, maybe some more lightweight solutions?

First we can add support for multi-line values like this, so all `dotenv` libraries support them:
```
MULTILINE="new\nline"
```

To do this, it will be enough to update `QuoteCharacterChecker`.

> We would need to read files at once and not line by line and write a parser I think which parses the `.env` file in our internal code structure I think. Sounds a bit complicated, I've never written a parser in my life but I would be interested.

This option is only supported by `bkeepers/dotenv`:
```
MULTILINE="new
line"
```

I think we can not support this option 🤔
What do you think?

**Comment by DDtKey** [comment]
> I think we can not support this option 🤔
> 

In that case, I agree

**Comment by mstruebing** [comment]
The goal somewhere in the future should be to be able to support something like:

```
MULTILINE="new
line"
```

But I think it would be hard work and the other way, to support `MULTILINE="new\nline"` is much easier and quicker to achieve.
So I think we should go for the quick solution for now.
