### ISSUE TITLE
How to use quote values inside a string?

### ISSUE THREAD

**Issue by ppankowski** [dotenv-linter/dotenv-linter#361]
Hi,

It's more a question than issue.

I've a .env entry that contains json array as string, like:

`
KEY=["value"]
`

which triggers QuoteCharacter check. How can I prevent this and is this the intended behaviour?

**Comment by mgrachev** [comment]
Hey @ppankowski!

You can disable `QuoteCharacter` only for some lines using [control comments](https://dotenv-linter.github.io/#/usage/check?id=skip-checks). For example:

```env
# .env

# dotenv-linter:off QuoteCharacter
KEY=["value"]
# dotenv-linter:on QuoteCharacter

```

**Comment by mstruebing** [comment]
I will close this issue as it has been answered.
