### ISSUE TITLE
README should shortly describe and link what ".env" files are.

### ISSUE THREAD

**Issue by vi** [dotenv-linter/dotenv-linter#362]
As far as I understood from README, ".env" files are some text files which can contain keys and values that live in programming projects.

But it should be more clear what `.env` files are used for.

**Comment by mstruebing** [comment]
Hey @vi great suggestion.
I think because most of us who are using and developing this tool is perfectly clear what `.env` files are, we missed the tiny thing to tell others who don't. I really like that suggestion :+1:
