### ISSUE TITLE
feature request: ensure that the file is not readable by everyone

### ISSUE THREAD

**Issue by bbigras** [dotenv-linter/dotenv-linter#365]
Often `.env` files have credentials in them. Maybe it would be nice to ensure it's only readable by the owner.

**Comment by mstruebing** [comment]
Hey @bbigras thank you for your idea.

To be honest, I don't really think that this should be part of this tool.
What do you think @dotenv-linter/core?

**Comment by mgrachev** [comment]
> To be honest, I don't really think that this should be part of this tool.
> What do you think @dotenv-linter/core?

@bbigras 👋 Thank you for your proposal, but I agree  with @mstruebing.
