### ISSUE TITLE
Print a message "Nothing to check"

### ISSUE THREAD

**Issue by mgrachev** [dotenv-linter/dotenv-linter#384]
### Description

Print a message "Nothing to check" in the absence of `.env` files for check.

### Implementation

**Step 1:**

Add a method for [CheckOutput](https://github.com/dotenv-linter/dotenv-linter/blob/master/src/common/output/check.rs#L11) to print the message "Nothing to check" only if `is_quiet_mode == false`.

**Step 2:**

Call the method from the step 1 when [lines_map](https://github.com/dotenv-linter/dotenv-linter/blob/master/src/lib.rs#L20) is empty.

**Step 3:**

Add integration tests [here](https://github.com/dotenv-linter/dotenv-linter/blob/master/tests/output/check.rs).

### Example

There aren't `.env` files in the current directory:

```sh
$ dotenv-linter
Nothing to check
```

**Comment by jodli** [comment]
I will look at this in the evening, if it's okay! :)

**Comment by mstruebing** [comment]
Sure, I assign you to that issue.
