### ISSUE TITLE
Print a message "Nothing to fix"

### ISSUE THREAD

**Issue by mgrachev** [dotenv-linter/dotenv-linter#385]
### Description

Print a message "Nothing to fix" in the absence of `.env` files for fix.

### Implementation

**Step 1:**

Add a method for [FixOutput](https://github.com/dotenv-linter/dotenv-linter/blob/master/src/common/output/fix.rs#L14) to print the message "Nothing to fix" only if `is_quiet_mode == false`.

**Step 2:**

Call the method from the step 1 when [lines_map](https://github.com/dotenv-linter/dotenv-linter/blob/master/src/lib.rs#L54) is empty.

**Step 3:**

Add integration tests [here](https://github.com/dotenv-linter/dotenv-linter/blob/master/tests/output/fix.rs).

### Example

There aren't `.env` files in the current directory:

```sh
$ dotenv-linter fix
Nothing to fix
```

**Comment by mdycz** [comment]
I'd like to take this if that's ok :)

**Comment by DDtKey** [comment]
I'll assign that issue to you 🙂
