### ISSUE TITLE
Print a message "Nothing to compare"

### ISSUE THREAD

**Issue by mgrachev** [dotenv-linter/dotenv-linter#386]
### Description

Print a message "Nothing to compare" in the absence of `.env` files for compare.

### Implementation

**Step 1:**

Add a method for [CompareOutput](https://github.com/dotenv-linter/dotenv-linter/blob/master/src/common/output/compare.rs#L8) to print the message "Nothing to compare" only if `is_quiet_mode == false`.

**Step 2:**

Call the method from the step 1 when [lines_map](https://github.com/dotenv-linter/dotenv-linter/blob/master/src/lib.rs#L105) is empty.

**Step 3:**

Add integration tests [here](https://github.com/dotenv-linter/dotenv-linter/blob/master/tests/output/compare.rs).

### Example

There aren't `.env` files in the current directory:

```sh
$ dotenv-linter compare .env1 .env2
Nothing to compare
```

**Comment by jakecorrenti** [comment]
Hi there, can I take this on as my first contribution?

**Comment by jakecorrenti** [comment]
is there a naming convention that you use for a new branch?

**Comment by jakecorrenti** [comment]
The link to show where the integration tests should go is broken, where would you like these implemented?

**Comment by mgrachev** [comment]
> The link to show where the integration tests should go is broken, where would you like these implemented?

Integration tests should be located in `tests/output/compare.rs`.

**Comment by jakecorrenti** [comment]
do you mean `tests/compare/compare.rs`? I don't see a `tests/output/compare.rs` unless I am supposed to actually create the file myself. I'm pretty new to this so I'm sorry for getting a little lost

**Comment by mgrachev** [comment]
> do you mean `tests/compare/compare.rs`? I don't see a `tests/output/compare.rs` unless I am supposed to actually create the file myself. I'm pretty new to this so I'm sorry for getting a little lost

Yes, you should create this file.
