### ISSUE TITLE
Replace String on Into<String> for all TestDir methods

### ISSUE THREAD

**Issue by mgrachev** [dotenv-linter/dotenv-linter#387]
### Description

We use the `TestDir` struct in our integrational tests. Some methods of this struct take `String` as an argument:
* [test_command_success](https://github.com/dotenv-linter/dotenv-linter/blob/master/tests/common/test_dir.rs#L71)
* [test_command_fail](https://github.com/dotenv-linter/dotenv-linter/blob/master/tests/common/test_dir.rs#L79)
* [test_command_success_with_args](https://github.com/dotenv-linter/dotenv-linter/blob/master/tests/common/test_dir.rs#L88)
* [test_command_fail_with_args](https://github.com/dotenv-linter/dotenv-linter/blob/master/tests/common/test_dir.rs#L108)
* [test_command_fix_success](https://github.com/dotenv-linter/dotenv-linter/blob/master/tests/common/test_dir.rs#L128)
* [test_command_fix_success_with_args](https://github.com/dotenv-linter/dotenv-linter/blob/master/tests/common/test_dir.rs#L154)

In some tests we convert `&str` to string using the `String::from` method:

```rust
// tests/output/check.rs
#[test]
fn problems() {
    let test_dir = TestDir::new();
    test_dir.create_testfile(".env", "abc=DEF\n");

    let expected_output = String::from(
        r#"Checking .env
.env:1 LowercaseKey: The abc key should be in uppercase

Found 1 problem
"#,
    );

    test_dir.test_command_fail(expected_output);
}
```

It would be great if these methods take `&str` as well.

### Implementation

We can do it using the `Into<String>` trait.

**Comment by ebobrow** [comment]
I'd like to try this one, if that's okay.

**Comment by mgrachev** [comment]
> I'd like to try this one, if that's okay.

I'll assign that issue to you 👍
