### ISSUE TITLE
Use Rc for LineEntry to reduce memory consumption

### ISSUE THREAD

**Issue by mgrachev** [dotenv-linter/dotenv-linter#388]
### Description

The `LineEntry` struct has the [FileEntry](https://github.com/dotenv-linter/dotenv-linter/blob/master/src/common/line_entry.rs#L7) field which clones for every `LineEntry` in the [get_line_entries](https://github.com/dotenv-linter/dotenv-linter/blob/master/src/lib.rs#L229) method.

Use the [Rc](https://doc.rust-lang.org/std/rc/index.html) type for `LineEntry` to reduce memory consumption.

### Implementation

**Step 1:**

Add a new method `new` for `LineEntry` which takes `file` as `Rc<FileEntry>`.

**Step 2:**

Use the method from step 1 to create the `LineEntry` struct in all places.

**Comment by Tom01098** [comment]
I'd like to take a stab at this one!

**Comment by mstruebing** [comment]
I'll assign you :muscle:
