### ISSUE TITLE
Add check: Substitution keys

### ISSUE THREAD

**Issue by DDtKey** [dotenv-linter/dotenv-linter#407]
Example: 

```shell
# .env

# Wrong
ABC=${BAR
FOO=$BAR}

# Correct
ABC=$BAR
FOO=${BAR}
FOO="$BAR"
```

You can find more details in #379 issue and [its implementation](https://github.com/dotenv-linter/dotenv-linter/blob/a3878621ef862fead0bf03f9344bfd45ffdad935/src/common/line_entry.rs#L92)  

And for other examples substitution keys, you can look at the [dotenv libraries that support variable substitution](https://github.com/dotenv-linter/dotenv-linter/issues/360#issuecomment-783316044).

> **The note:** 
> Read how to write a new checker on  [CONTRIBUTING.md](https://github.com/dotenv-linter/dotenv-linter/blob/master/CONTRIBUTING.md)

**Comment by de-sh** [comment]
Hey, I am trying to solve this issue. Can I get a review of my work so far: https://github.com/de-sh/dotenv-linter/commit/49d099cc175270f2e611ed571582bccf67ef1840

**Comment by mgrachev** [comment]
> Hey, I am trying to solve this issue. Can I get a review of my work so far: [de-sh@49d099c](https://github.com/de-sh/dotenv-linter/commit/49d099cc175270f2e611ed571582bccf67ef1840)
> 
> Does it look like its ready to open a PR with?

Thank you for your interest!

A quick glance showed that it's ready for review 👍 Please, open the PR with these changes.
I guess there will be several questions, but it's okay 🙂
