### ISSUE TITLE
Fix QuoteCharacterChecker for values with substitution keys

### ISSUE THREAD

**Issue by DDtKey** [dotenv-linter/dotenv-linter#408]
### Description
`dotenv-linter` shouldn't create a `Warning` If the value of the variable contains `$` character, because it might be an escaped substitution variable.

### TODO: 
* Return `None` from  `QuoteCharacterChecker` if value contains `$` character. You can do this here:
https://github.com/dotenv-linter/dotenv-linter/blob/a3878621ef862fead0bf03f9344bfd45ffdad935/src/checks/quote_character.rs#L27

**Comment by romerorocha** [comment]
Hi! I've started learning Rust a few months ago. This seems to be pretty simple and I'd like to learn and help :)

I mean, the solution is as simple as
`
if val.contains("\\n") || val.contains(char::is_whitespace) || val.contains('$') {
    return None;
}
`
right?

Could I be assigned to it?

**Comment by JuanMarchetto** [comment]
Hello, I am interested in solve this one.

**Comment by DDtKey** [comment]
Ok I'll assign it to you.
