### ISSUE TITLE
Fix the possibility of incorrectly fixing of the ENV file

### ISSUE THREAD

**Issue by DDtKey** [dotenv-linter/dotenv-linter#409]
### Description 
`Fixers` can return `None` for cases when didn't fix anything.

But we don't compare the number of `Warnings` and the number of fixes.
We only check that there was at least 1 fix:
https://github.com/dotenv-linter/dotenv-linter/blob/a3878621ef862fead0bf03f9344bfd45ffdad935/src/lib.rs#L73

I believe this should be considered as an `Error` and not normal behavior. Since disagreements will be difficult to spot.
This was partially discussed here: [link](https://github.com/dotenv-linter/dotenv-linter/pull/406#discussion_r605201385).
As a rule, such situations shouldn't arise when the program is working correctly. But it's not right to ignore them.

We should print text that we couldn't correct all errors.

### TODO

- Compare the number of fixes returned by`fixes::run` and the expected number of fixed warnings. 
- If they differ, print to the console the text about the impossibility of fixing all warnings

**Comment by oren0e** [comment]
I might want to try and tackle this, but note that I'm a beginner in Rust (read the first 13 chapters in the rust book so far), done some minor stuff.

**Comment by mgrachev** [comment]
> I might want to try and tackle this, but note that I'm a beginner in Rust (read the first 13 chapters in the rust book so far), done some minor stuff.

There is already a PR for this issue, please choose another one 😉
