### ISSUE TITLE
AUR version is outdated

### ISSUE THREAD

**Issue by mgrachev** [dotenv-linter/dotenv-linter#412]
Link: https://aur.archlinux.org/packages/dotenv-linter-git

<img width="518" alt="Screenshot 2021-04-05 at 12 15 12" src="https://user-images.githubusercontent.com/700998/113558701-ce4d2880-9608-11eb-80df-a9ce1880d992.png">

@mstruebing Can you take a look what is wrong with the release process to AUR?

**Comment by mstruebing** [comment]
This package is up to date. It is the `-git` package of `dotenv-linter` which means it takes the current master branch and builds it on your computer. You will need to take care of updates yourself but can do them whenever you want on your own computer.

As you can see here in line 23-25: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=dotenv-linter-git#n23
It takes the master/default branch and builds a production release.

The version and last updated fields are referencing the way how the package is build. So, whenever this changes the last updated and version will increase, but as it is still the same, it doesn't need an update.

How that clarifies a bit. If you want to install a precompiled binary you can take the package with the `-bin` suffix, this should also have the correct values of version and last updated inside.(https://aur.archlinux.org/packages/dotenv-linter-bin/)

**Comment by mgrachev** [comment]
Thank you for explaining me and now I see that everything is fine.

There is only one question left - Can we remove the version number `1.1.0.r4.g61ff93d-1` from the https://aur.archlinux.org/packages/dotenv-linter-git page?

**Comment by mstruebing** [comment]
We can not remove it. 
It is the same as what you can see in line 4 (and 16-19): https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=dotenv-linter-git#n4

We could choose our own and set any specific version. One thing that came to my mind would be to update that pkgver on every release, which might be a good solution.

I will think about it and maybe will provide a PR. :)

**Comment by mstruebing** [comment]
After thinking of this: We should not adjust the version number on every release. This package takes the latest upstream/master version and builds it on your local computer. That is common on AUR packages with `-git` suffix, and a well known and accepted pattern.

So we could agree on a specific version for now, which needs to be updated if the way the package is built changes.
We can not remove the version number as this is needed for the AUR-tooling to work correctly.

Either we just stick to that current version (and of course update it after semver specifications if it changes, then we could remove the latest part after the specific version number) or adjust it to something like 1.1.1.

When I released the package I "accidentally" (or on purpose?) used this `git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g' | sed 's/^v//g'` on the dorenv-linter repo to generate a unique version number.

**Comment by mgrachev** [comment]
> adjust it to something like 1.1.1.

I would choose this option. What do you think about it?

**Comment by mstruebing** [comment]
I would be okay with this. If no one has objections until tomorrow I will do it tomorrow.

**Comment by mstruebing** [comment]
https://aur.archlinux.org/packages/dotenv-linter-git/
