### ISSUE TITLE
Use enum instead of string for lint's identity

### ISSUE THREAD

**Issue by atsmtat** [dotenv-linter/dotenv-linter#426]
Currently, lints are recognized using string -- "DuplicatedKey", "EndingBlankLine" etc.  
It could be done by defining an `Enum` -- something like:
```rust
enum Lint {
   DuplicatedKey,
   EndingBlankLine,
   ExtraBlankLine,
   // ...
}
```

And use it in place of `&str` for `Warning::check_name`, `Check::name`, and `Fix::name`. `Lint` can implement `Display` for printing purposes. This way, we avoid string comparison (faster code), and get safety against typos in using strings (compile time checks).

**Comment by fabricio7p** [comment]
Is this free for assignment? I would love to help if you guys could give me a hand as a mentored issue

**Comment by mgrachev** [comment]
> Is this free for assignment? I would love to help if you guys could give me a hand as a mentored issue

I'll assign it to you 👍
