### ISSUE TITLE
Apple Silicon (m1)

### ISSUE THREAD

**Issue by b1rdex** [dotenv-linter/dotenv-linter#435]
`dotenv-linter installer: Error: Unsupported architecture arm64. Only x86_64 binaries are available`

**Comment by DDtKey** [comment]
Hello, thanks for the issue.

It's my little shame, because I actively use m1, but forgot about native `dotenv-linter` support.
I'm using dotenv-linter in docker or via clippy 😅 

I have already made a PR, but until the release is released, you can also use alternative installation methods

**Comment by DDtKey** [comment]
@b1rdex new version has been released!
Now you can install `dotenv-linter` via a shell on Apple Silicon (m1):
```sh
curl -sSfL https://git.io/JLbXn | sh -s
dotenv-linter installer: The latest version will be installed.
dotenv-linter installer: Successfully installed dotenv-linter 3.1.1 to ./bin/dotenv-linter
```
