### ISSUE TITLE
Missing arm(64) docker builds

### ISSUE THREAD

**Issue by githubcdr** [dotenv-linter/dotenv-linter#449]
Hi,

Any plans to support other architectures for the Docker dotenv-linter image ?

**Comment by mstruebing** [comment]
Hey, @githubcdr thanks for your question.
I think there is nothing planned right now, but in theory, it shouldn't be that complicated I think.

I think we would need to add actions for releasing different architectures here when a release is triggered: https://github.com/dotenv-linter/dotenv-linter/blob/master/.github/workflows/release.yml#L87-L100

I'm not sure if this can be done in Github Actions, as far as I know, you need to be on that architecture you want to build the docker image for. That means we are dependent on what Github Actions provide.

In case Github Actions provides such architectures to run on or it is possible to cross-compile from a different architecture, it will be definitely worth adding.

**Comment by mstruebing** [comment]
These two links could help:
https://medium.com/swlh/using-github-actions-to-build-arm-based-docker-images-413a8d498ee
https://pet2cattle.com/2021/09/build-multiarch-container-github-action
