### ISSUE TITLE
recursive fix finds no files

### ISSUE THREAD

**Issue by thelittlebug** [dotenv-linter/dotenv-linter#498]
i think this screenshot is helpful, latest version installed as binary

![image](https://user-images.githubusercontent.com/2874956/161546096-416e57e0-4efa-4baa-97a2-bbcdc8fe77d5.png)

**Comment by mgrachev** [comment]
Yes, it's a bug. Thank for your feedback 👍

**Comment by CfirTsabari** [comment]
I looked into this, thought about trying to fix it, it related to how Clap subcommand work. 
Clap parse the `-r` to be part of the main command arguments, So using a `dotenv-linter fix -r` will work

**Comment by thelittlebug** [comment]
i have tested it and it works. thank you very much :)
