### ISSUE TITLE
Add environment variable for --not-check-updates

### ISSUE THREAD

**Issue by mwgamble** [dotenv-linter/dotenv-linter#593]
In certain environments, it may not be feasible to control all invocations of dotenv-linter. However the environment can typically still be controlled (and usually more easily even if invocations can be controlled). It would be nice if there was a way to set this with an environment variable.

**Comment by mgrachev** [comment]
Good idea, thanks!

**Comment by mwgamble** [comment]
@mgrachev I was working on a PR for this. The logic changes are very simple, literally two lines:

https://github.com/mwgamble/dotenv-linter/commit/cdb27d3094e9c4098995f6cd826a950e9dcb354d

I then went to add some tests, and came across this file:

https://github.com/dotenv-linter/dotenv-linter/blob/master/tests/flags/check_updates.rs

While trying to understand how the tests worked, I tried breaking them. The problem was, I wasn't able to break them:

#598 
#599 

I don't understand why, and therefore I'm not sure how I should go about implementing new tests for the new feature.

**Comment by mgrachev** [comment]
Are your questions still relevant?
