### ISSUE TITLE
Confusing behaviour when using --skip

### ISSUE THREAD

**Issue by mwgamble** [dotenv-linter/dotenv-linter#600]
If I pass `--skip SpecificCheck`, it eats all of the remaining arguments. If I do the traditional Unix thing of specifying flags before arguments, like so:

```
dotenv-linter --skip QuoteCharacter my/folder/.env
```

It completely ignores the fact that I passed a custom filename, and only checks for a `.env` file in the current folder. If such a file exists, it checks it. If no such file exists, it exits with a success status code (`0`).

If I pass the flag _after_ the list of files to check, everything works as expected:

```
dotenv-linter my/folder/.env --skip QuoteCharacter
```

It turns out I can make the first example work by doing this:

```
dotenv-linter --skip QuoteCharacter -- my/folder/.env
```

However this is uncommon for a CLI app, and isn't mentioned as a supported behaviour in the documentation. Also I don't see any tests that cover the case of skipping checks while also passing a custom list of files.

I think the ideal solution would be to allow flags to be passed in any order. Skipping multiple checks should require passing `--skip` multiple times.

**Comment by mwgamble** [comment]
I can't help but wonder if some of these issues are symptoms of not having a dedicated `check` subcommand. It seems like the issue I've highlighted is at least in part a symptom of the inevitable ambiguities that come with this decision.

**Comment by DDtKey** [comment]
It's related to list of arguments. You can pass several checks to skip argument, like:
```shell
dotenv-linter --skip Check1 Check2
```

So in your example the issue related to not using terminator. But as can I see, current code doesn't configured well.
We need to add either 
1. value [terminator](https://docs.rs/clap/4.0.27/clap/struct.Arg.html#method.value_terminator), so it will work in this way:
```sh
dotenv-linter --skip Check1 Check2 ; my/folder
```
2. or [delimiter](https://docs.rs/clap/4.0.27/clap/struct.Arg.html#method.value_delimiter):
```sh
dotenv-linter --skip Check1,Check2
```

It also will fix #601

@dotenv-linter/core it could be easily fixed [here](https://github.com/dotenv-linter/dotenv-linter/blob/master/src/cli.rs#L70-L77), but it's better to decide which way we would prefer.

**Comment by mwgamble** [comment]
Won't using a semicolon as a terminator conflict with typical usage in the shell, where a semi-colon denotes the end of a command? Asking users to escape a semi-colon isn't a particularly nicely user experience.

**Comment by DDtKey** [comment]
It will works fine, it's clap responsibility. You don't need to escape anything

**Comment by mgrachev** [comment]
I like the idea of using a delimiter more:
```
$ dotenv-linter --skip Check1,Check2
```
