### ISSUE TITLE
Support skipping specific checks with an environment variable

### ISSUE THREAD

**Issue by mwgamble** [dotenv-linter/dotenv-linter#601]
Clap supports accepting multiple values in a single environment variable:

https://docs.rs/clap/3.1.10/clap/struct.Arg.html#method.env

This could be used to implement something like this:

```
DOTENV_LINTER_SKIP=QuoteCharacter,UnorderedKey dotenv-linter
```

**Comment by NavinShrinivas** [comment]
Hey there, I'd like to have a go at this Issue. 

Does this new way of adding skips mean we remove the previous "--skip"?

**Comment by DDtKey** [comment]
@NavinShrinivas Hey! No, take a look at [this comment](https://github.com/dotenv-linter/dotenv-linter/issues/600#issuecomment-1330648089), please

**Comment by mwgamble** [comment]
Not stale.

**Comment by YeswanthRajakumar** [comment]
🥳
