### ISSUE TITLE
About release 3.3.0

### ISSUE THREAD

**Issue by chenrui333** [dotenv-linter/dotenv-linter#612]
👋 Looks like the [artifact got changed](https://github.com/Homebrew/homebrew-core/pull/118941) per homebrew's regression testing, just to raise this issue to confirm if that is intentional. Thanks!

**Comment by mgrachev** [comment]
Hey! Yes, the first release was erroneous.

**Comment by chenrui333** [comment]
Cool, cool, thanks for confirming it!
