### ISSUE TITLE
Incorrect fix for JSON string env vars

### ISSUE THREAD

**Issue by ducminh-phan** [dotenv-linter/dotenv-linter#673]
Currently, we are using [pydantic](https://docs.pydantic.dev/latest/usage/settings/#parsing-environment-variable-values) to read settings from environment variables. For complex types, `list[str]` for example, the values need to be JSON-encoded strings. For example,

```
FOO='["a","b"]'
```

With this dotenv file, `dotenv-linter fix` changes the file to

```
FOO=[a,b]
```

The value now is not a valid JSON string, therefore, `pydantic` could not parse the environment variable.

`FOO='["a", "b"]'` works, since it has a space in the value, but there's no workaround for `FOO='["a"]'`.

**Comment by mgrachev** [comment]
@ducminh-phan Hi 👋 Thank you for your feedback!

[We decided](https://github.com/dotenv-linter/dotenv-linter/pull/678#discussion_r1224621044) not to support JSON arrays in out tool.

> FOO='["a", "b"]' works, since it has a space in the value, but there's no workaround for FOO='["a"]'.

As a workaround, use the control comment to disable this check:
```
# dotenv-linter:off QuoteCharacter
FOO='["a"]'
# dotenv-linter:on QuoteCharacter
```

**Comment by ducminh-phan** [comment]
@mgrachev Thanks for getting back. I understand the decision to not support JSON string env vars. `# dotenv-linter:off QuoteCharacter` is good enough for my usecase 👍
