### ISSUE TITLE
allow settings to skip rules

### ISSUE THREAD

**Issue by woutervh** [dotenv-linter/dotenv-linter#725]
Just discovered dotenv-linter today,
but I standardize my env-files  on single-quote for constants and double-quote for variable subsitutions.
Hence all my files fail where they shouldn't.

allow rules to be skipped:
- support via cli
- support toml-configfile   ( env-var DOTENV_LINTER_CFG_FILE)
- support [tool:dotenv-linter]-section  in pyproject.toml

**Comment by DDtKey** [comment]
You can skip checks with CLI or control comments in env files:
https://dotenv-linter.github.io/#/usage/check?id=skip-checks

**Comment by mgrachev** [comment]
@woutervh I guess @DDtKey solved your problem. If not, then reopen the issue.
