### ISSUE TITLE
pip install dotenv-linter?

### ISSUE THREAD

**Issue by woutervh** [dotenv-linter/dotenv-linter#726]
Hello

Are the instruction on the homepage still correct?
see https://dotenv-linter.readthedocs.io/en/latest/

 dotenv-linter is a python-package on pypi latest release 0.4

**Comment by DDtKey** [comment]
Hi, you likely confuse the project with: https://github.com/wemake-services/dotenv-linter

**Comment by woutervh** [comment]
I thought the initial implementation was in python up to v 0.4
and then reimplemented in rust starting fom v1.0.

But these projects are both active and completely unrelated? 
Sure that is confusing.

**Comment by mgrachev** [comment]
I'll close the issue. If you still have questions, reopen it.
