### ISSUE TITLE
Please update the ring crate to 17.x

### ISSUE THREAD

**Issue by yurivict** [dotenv-linter/dotenv-linter#742]
This is needed to prevent failures like [this](https://github.com/briansmith/ring/issues/1904).

**Comment by mgrachev** [comment]
Hi, @yurivict  👋

We don't depend on `ring` directly, it's a transitive dependency.

**Comment by yurivict** [comment]
@mgrachev 

```rustls``` already uses ring-17.x
Could you please update to the latest ```rustls``` 0.22.2 ?
