### ISSUE TITLE
how to use as a lsp

### ISSUE THREAD

**Issue by ulic-youthlic** [dotenv-linter/dotenv-linter#792]
Hi,

I would like to integrate dotenv-linter as lsp with my editor. This would provide checks in real time while editing dotenv files. Is there any way to achieve this at the moment?

thx.

**Comment by mgrachev** [comment]
@ulic-youthlic 👋 Thank you for your feedback!

We don't have that option right now, but we have a plan to split this project into several crates and provide an API.

**Comment by ulic-youthlic** [comment]
Thanks 🙏 for your reply, I am aware of the situation.
